sources:
  - name: Neuroscience News
    type: website
    category: news
    url: "https://neurosciencenews.com/"

  - name: Eventbrite Neuroscience Events
    type: api
    category: events
    url: "https://www.eventbriteapi.com/v3/events/search/"
    params:
      token: "YOUR_EVENTBRITE_API_TOKEN"

  - name: YouTube Neuroscience Videos
    type: api
    category: videos/courses
    url: "https://www.googleapis.com/youtube/v3/search"
    params:
      key: "YOUR_YOUTUBE_API_KEY"
      q: "neuroscience videos"

  - name: Neuroscience Fun Facts
    type: website
    category: facts
    url: "https://example-facts-source.com/"